# Generated by Django 4.1.1 on 2024-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veriproje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Boy', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
