# Generated by Django 4.1.1 on 2024-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veriproje', '0003_dosya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosya2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.CharField(max_length=255)),
                ('javadoc_sayisi', models.IntegerField()),
                ('yorum_sayisi', models.IntegerField()),
                ('kod_sayisi', models.IntegerField()),
                ('loc_sayisi', models.IntegerField()),
                ('fonksiyon_sayisi', models.IntegerField()),
                ('yorum_sapma_yuzdesi', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dosya',
        ),
    ]
