# Generated by Django 4.1.1 on 2024-03-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veriproje', '0004_dosya2_delete_dosya'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kisi',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
